version: '3.8'
services:
  portal_db:
    container_name: portal_db
    image: 'mysql:8.0'
    restart: always
    environment:
      MYSQL_DATABASE: db_wordpress
      MYSQL_USER: usr_wordpress
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - './mysql:/var/lib/mysql'
    ports:
      - '3308:3306'
    networks:
      plai:
        ipv4_address: 172.23.0.7
  portal_wordpress:
    container_name: portal_wordpress
    depends_on:
      - portal_db
    image: plai/portal
    build: .
    restart: always
    ports:
      - '8002:80'
    environment:
      WORDPRESS_DB_HOST: portal_db
      WORDPRESS_DB_USER: usr_wordpress
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: db_wordpress
    volumes:
      - './wordpress:/var/www/html'
    networks:
      plai:
        ipv4_address: 172.23.0.6
volumes:
  .: null
networks:
  plai:
    external: false
    name: plai
    ipam:
      config:
        - subnet: 172.23.0.0/16
